### PR TITLE
GCI-11: Add missing maven formatter plugin for OpenMRS modules

### PR DESCRIPTION
**Pull request by teleivo**
done as discussed here:
https://issues.openmrs.org/browse/GCI-11

### CODE REVIEW

**Comment by sunbiz** [comment]
Are the changes to the files coming after applying the formatter?

**Comment by teleivo** [comment]
Yes, first commit is adding the java-formatter Plugin and the second commit is applying the auto-formatting. Thought this is a good idea

**Comment by sunbiz** [comment]
Yes, good idea indeed... I was looking at the enum formatter pull request and core. In that you haven't committed the changed code due to the formatter. I can commit those, unless you want to add it to your pull request to core?

**Comment by teleivo** [comment]
No, would be great if you could merge this one. It doesn't have the changes
I added to the formatter in the pull request with an enum element per line
yet but we only have one enum in the radiology module at the moment. So for
now this would be great to get started :) thanks a lot!
Am 07.03.2015 02:52 schrieb "Saptarshi Purkayastha" <
notifications@github.com>:

**Pull request merged**
